Models/ContactViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace coreapp.Models
{
    public class ContactViewModel
    {
        public string Param { get; set; }  
        [Required]
        [MaxLength(250, ErrorMessage = "Too Long.")]
        public string Name { get; set; } 
    }
}

Controllers/AppController.cs
using System;
using coreapp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace coreapp.Controllers
{
    public class AppController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet("contact")]
        public IActionResult Contact()
        {
            ViewBag.Title = "Contact us";
            //throw new Exception("Bad things happen");
            return View();
        }
       
        [HttpPost("contact")]
        public IActionResult Contact(ContactViewModel model)
        {
            return View();
        }

        [HttpGet("product")]
        public IActionResult Product()
        {
            ViewBag.Title = "Contact us";
            //throw new Exception("Bad things happen");
            return View();
        }

        [Authorize]
        [HttpGet]
        public IActionResult Shop()
        {
          try
          {
            
            return Ok();
          }
          catch (Exception)
          {
            return BadRequest();
          }
        }
    }
}

Controllers/ValuesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace coreapp.Controllers
{
    [Route("api/[controller]")]
    public class ValuesController : Controller
    {
        // GET api/values
        [HttpGet]
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }

        // GET api/values/5
        [HttpGet("{id}")]
        public string Get(int id)
        {
            return "value";
        }

        // POST api/values
        [HttpPost]
        public void Post([FromBody]string value)
        {
        }

        // PUT api/values/5
        [HttpPut("{id}")]
        public void Put(int id, [FromBody]string value)
        {
        }

        // DELETE api/values/5
        [HttpDelete("{id}")]
        public void Delete(int id)
        {
        }
    }
}

Views/App/Index.cshtml
@{
  ViewBag.Title = "HomePage";
}

<h1>
  Home Page
</h1>

Views/App/contact.cshtml
@model ContactViewModel

<h1>Contact Page</h1>

<form method="post" asp-controller="app" asp-action="Contact">
    <label asp-for="Param"></label>
    <input type="text" asp-for="Param" />
    <label asp-for="Name"></label>
    <input type="text" asp-for="Name" />

    <br>
    <input type="submit" value="Send"/>
</form>

Views/App/product.cshtml
<h1>Product Page</h1>

<form method="post">
    <input type="text" />
    <input type="submit" value="Send"/>
</form>

Views/App/shop.cshtml
<h1>Shop Page</h1>

<form method="post">
    <input type="text" />
    <input type="submit" value="Send"/>
</form>

Views/Shared/_Layout.cshtml
<html>
    <head>
        <title>
            @ViewBag.Title
        </title>
        <link rel="stylesheet" href="~/Content/bootstrap.min.css">
        <link rel="stylesheet" href="~/Content/bootstrap-theme.min.css">    
        <script src="~/Content/jquery.min.js"></script>
        <script src="~/Content/bootstrap.min.js"></script>
    </head>
    <body>    
            <nav class="navbar navbar-default" role="navigation">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                      </button>
                      <a class="navbar-brand" href="#">Title</a>
                    </div>
                  
                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse navbar-ex1-collapse">
                      <ul class="nav navbar-nav">
                        <li class="active"><a asp-controller="App" asp-action="Contact">Contact</a></li>
                        <li><a asp-controller="App" asp-action="Product">Product</a></li>
                        <li><a asp-controller="App" asp-action="Shop">Shop</a></li>
                      </ul>
                      <form class="navbar-form navbar-left" role="search">
                        <div class="form-group">
                          <input type="text" class="form-control" placeholder="Search">
                        </div>
                        <button type="submit" class="btn btn-default">Submit</button>
                      </form>
                      <ul class="nav navbar-nav navbar-right">
                        <li><a href="#">Link</a></li>
                        <li class="dropdown">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                          <ul class="dropdown-menu">
                            <li><a href="#">Action</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li><a href="#">Separated link</a></li>
                          </ul>
                        </li>
                      </ul>
                    </div><!-- /.navbar-collapse -->
                  </nav>
                       
        @RenderBody()
    </body>
    <!-- @RenderSection("scripts",false) -->
</html>